INSERT INTO DISCOGRAPHY.ARTIST (ID, NAME) VALUES (101 ,'Artist 1')
INSERT INTO DISCOGRAPHY.ARTIST (ID, NAME) VALUES (102, 'Artist 2')

INSERT INTO DISCOGRAPHY.ALBUM (ID, RELEASE, TITLE, ARTIST_ID) VALUES (101, '2001', 'Album 1', 101)
INSERT INTO DISCOGRAPHY.ALBUM (ID, RELEASE, TITLE, ARTIST_ID) VALUES (102, '2002', 'Album 2', 101)
INSERT INTO DISCOGRAPHY.ALBUM (ID, RELEASE, TITLE, ARTIST_ID) VALUES (103, '2003', 'Album 3', 101)

INSERT INTO DISCOGRAPHY.TRACK (ID, TRACK,ALBUM_ID) VALUES (101, 'Track 1',101)
INSERT INTO DISCOGRAPHY.TRACK (ID, TRACK,ALBUM_ID) VALUES (102, 'Track 2',101)
INSERT INTO DISCOGRAPHY.TRACK (ID, TRACK,ALBUM_ID) VALUES (103, 'Track 3',101)